<?php

/**
 * hook_menu implementation.
 * 
 * @return array
 */
function yass_ui_menu() {
  $items = array();
  
  $items['yass'] = array(
      'title'  => 'Sync Console',
      'file'             => 'yass_ui.console.inc',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('yass_ui_console'),
      'access callback'  => 'user_access',
      'access arguments' => array('administer CiviCRM'),
      'type'             => MENU_CALLBACK,
  );
  ## yass/entity/REPLICANAME/ENTITYID[/U_REPLICA:U_TICK]
  $items['yass/entity/%'] = array(
      'title'  => 'Inspect Entity',
      'file'             => 'yass_ui.pages.inc',
      'page callback'    => 'yass_ui_pages_entity',
      'page arguments'   => array(2,3,4),
      'access callback'  => 'user_access',
      'access arguments' => array('administer CiviCRM'),
      'type'             => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * hook_theme implementation
 */
function yass_ui_theme() {
  return array(
    'yass_ui_entity' => array(
      'template' => 'yass_ui_entity',
      'arguments' => array('replica' => NULL, 'entity' => NULL, 'entityFilterLog' => NULL, 'revisions' => NULL),
    ),
    'yass_ui_filter_log' => array(
      'template' => 'yass_ui_filter_log',
      'arguments' => array('entityFilterLog' => NULL),
    ),
    'yass_ui_revisions' => array(
      'template' => 'yass_ui_revisions',
      'arguments' => array('revisions' => NULL),
    ),
    'yass_ui_console_status' => array(
      'template' => 'yass_ui_console_status',
      'arguments' => array('replicas' => NULL, 'lastSeens' => NULL, 'lastRuns' => NULL),
    ),
    'yass_ui_console_log' => array(
      'template' => 'yass_ui_console_log',
      'arguments' => array('log_pager' => NULL),
    ),
  );
}
