<?php

/**
 * Implementation of hook_yass_replicas
 */
function yass_replica_master_yass_replicas() {
  return array(
    'master' => array(
      'name' => 'master',
      'datastore' => 'GenericSQL',
      'syncstore' => 'GenericSQL',
      'is_active' => TRUE,
    ),
  );
}

/**
 * Implementation of hook_cron
 */
function yass_replica_master_cron() {
  yass_arms_clear();
  require_once 'YASS/Engine.php';
  require_once 'YASS/ConflictResolver/Exception.php';
  $conflictResolver = new YASS_ConflictResolver_Exception(); // FIXME: Need a better policy
  YASS_Engine::singleton()->syncAll( YASS_Engine::singleton()->getReplicaByName('master'),  $conflictResolver);
}
