<?php

/*
 +--------------------------------------------------------------------+
 | YASS                                                               |
 +--------------------------------------------------------------------+
 | Copyright ARMS Software LLC (c) 2011-2012                          |
 +--------------------------------------------------------------------+
 | This file is a part of YASS.                                       |
 |                                                                    |
 | YASS is free software; you can copy, modify, and distribute it     |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007.                                       |
 |                                                                    |
 | YASS is distributed in the hope that it will be useful, but        |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | Additional permissions may be granted. See LICENSE.txt for         |
 | details.                                                           |
 +--------------------------------------------------------------------+
*/

/**
 * Implementation of hook_perm
 */
function yass_replica_arms_perm() {
  return array(
    'access yass guid',
  );
}

/**
 * Implementation of hook_yass_replicas
 */
function yass_replica_arms_yass_replicas() {
  return array(
    'arms' => array(
      'name' => 'arms',
      'datastore' => 'CiviCRM',
      'syncstore' => 'CiviCRM',
      'is_active' => TRUE,
      'is_triggered' => TRUE,
    ),
  );
}

/**
 * Implementation of hook_drush_command
 */
function yass_replica_arms_drush_command() {
  module_load_include('drush.inc', 'yass_replica_arms');
  $items = array();
  $items['yass-arms-contact'] = array(
    'callback' => '_yass_replica_arms_drush_contact',
    'description' => 'Print details information about a replica. Params: <contact-guid>',
  );
  return $items;
}

/**
 * Implementation of hook_civicrm_pageRun
 */
function yass_replica_arms_civicrm_pageRun(&$page) {
  if ($page instanceof CRM_Contact_Page_View_Tabbed) {
    if (!user_access('access yass guid')) return;
    
    $masterSiteId = arms_interlink_master_site();
    if (!$masterSiteId) return;
    
    require_once 'YASS/Engine.php';
    $replica = YASS_Engine::singleton()->getReplicaByName('arms');
    if (!$replica) return;
    
    $guid = check_plain($replica->mapper->toGlobal('civicrm_contact', $_REQUEST['cid']));
    if (!$guid) {
      drupal_set_message(t('Failed to determine contact GUID'), 'warning');
      return;
    }
    
    $page->assign('contactGuid', $guid);
    $page->assign('contactGuidUrl', arms_interlink_url(arms_interlink_get($masterSiteId), "yass/entity/master/$guid"));
  }
}
